# 1. Conexão com o PostgreSQL via Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/livrariadb
spring.datasource.username=marcos
spring.datasource.password=12345

# 2. Configurações do JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 3. A MUDANÇA DE PARADIGMA: O Hibernate não cria mais as tabelas!
# Agora ele apenas "valida" se o banco está igual ao código Java.
# Quem cria as tabelas agora é o Flyway.
spring.jpa.hibernate.ddl-auto=validate

