spring.application.name=api-livraria
# Nome fixo do banco de dados (para não mudar senha/url toda vez)
spring.datasource.url=jdbc:h2:mem:livraria-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL que o Hibernate está gerando no console (bom para aprender)
spring.jpa.show-sql=true

# Habilita o painel visual do banco
spring.h2.console.enabled=true
