### 1. Cadastrar um Autor primeiro
POST http://localhost:8080/autores
Content-Type: application/json

{
  "nome": "J.R.R. Tolkien",
  "biografia": "Escritor britânico e professor universitário."
}

### Cadastrar o Livro apontando para o Autor 1
POST http://localhost:8080/livros
Content-Type: application/json

{
  "tipo": "FISICO",
  "titulo": "O Senhor dos Anéis",
  "paginas": 1200,
  "genero": "FICCAO",
  "preco": 150.0,
  "dataLancamento": "1954-07-29",
  "autorId": 1
}

###Cadastro de Ebook para o autor 1
POST http://localhost:8080/livros
Content-Type: application/json

{
  "tipo": "EBOOK",
  "titulo": "O Senhor dos Anéis",
  "paginas": 1200,
  "genero": "FICCAO",
  "preco": 100.0,
  "dataLancamento": "1954-07-29",
  "autorId": 1,
  "marcaDagua": "Livraria Wow"
}

### 3. Atualização do put com id e formatado com dto de cadastro.
PUT http://localhost:8080/livros/1
Content-Type: application/json

{
  "tipo": "FISICO",
  "titulo": "O Senhor dos Anéis",
  "paginas": 1200,
  "genero": "FICCAO",
  "preco": 99.0,
  "dataLancamento": "1954-07-29",
  "autorId":1
}

### Aplicar Desconto de 10%
PUT http://localhost:8080/livros/1/aplicar-desconto
Content-Type: application/json

{
  "percentual": 10
}

### Listar Todos
GET http://localhost:8080/livros

### Listar a primeira página (página 0), com 2 livros por página
GET http://localhost:8080/livros?page=0&size=2

### Listar a segunda página (página 1), com 2 livros por página
GET http://localhost:8080/livros?page=1&size=2

### Listar ordenando pelo preço mais barato primeiro
GET http://localhost:8080/livros?size=5&sort=preco,asc

### Buscar Livro que EXISTE (Primeiro cadastre um livro!)
GET http://localhost:8080/livros/1

### Buscar Livro que NÃO EXISTE
GET http://localhost:8080/livros/999

### Deletar Livro ID 1
DELETE http://localhost:8080/livros/1

### Deletar Livro que não existe
DELETE http://localhost:8080/livros/999

### Buscar Autor e seu portfólio de livros
GET http://localhost:8080/autores/1