CREATE TABLE autor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    biografia TEXT
);

CREATE TABLE livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor_id BIGINT NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    paginas INTEGER NOT NULL,
    genero VARCHAR(255) NOT NULL,
    data_publicacao DATE,

    CONSTRAINT fk_autor FOREIGN KEY (autor_id) REFERENCES autor(id)
);

CREATE TABLE ebook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tamanho_mb DOUBLE PRECISION,
    marca_dagua VARCHAR(255),

    constraint fk_ebook_livro FOREIGN KEY (id) REFERENCES livro(id)
);

CREATE TABLE fisico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peso_gramas INTEGER,
    quantidade_estoque INTEGER,

    CONSTRAINT fk_fisico_livro FOREIGN KEY (id) REFERENCES livro(id)
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) UNIQUE NOT NULL,
    descricao TEXT
);

CREATE TABLE livro_tag (
    livro_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    CONSTRAINT pk_livro_tag PRIMARY KEY (livro_id, tag_id),

    CONSTRAINT fk_livro FOREIGN KEY (livro_id) REFERENCES livro (id),
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

-- 1. Tabela de Compras (Histórico definitivo)
CREATE TABLE compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    data_compra TIMESTAMP NOT NULL,
    valor_pago DECIMAL(10,2) NOT NULL,

    -- Chaves Estrangeiras garantem que não podemos vender para um usuário fantasma ou um livro deletado
    CONSTRAINT fk_compra_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_compra_livro FOREIGN KEY (livro_id) REFERENCES livro(id)
);

-- 2. Tabela de Empréstimos (Transação com ciclo de vida)
CREATE TABLE emprestimo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    data_emprestimo TIMESTAMP NOT NULL,
    data_devolucao_prevista TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_emprestimo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_emprestimo_livro FOREIGN KEY (livro_id) REFERENCES livro(id)
);