CREATE TABLE author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        biography TEXT
);

CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      author_id BIGINT NOT NULL,
                      price DECIMAL(10,2) NOT NULL,
                      pages INTEGER NOT NULL,
                      genre VARCHAR(255) NOT NULL,
                      publication_date DATE,

                      CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE ebook (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       size_mb DOUBLE PRECISION,
                       watermark VARCHAR(255),

                       constraint fk_ebook_book FOREIGN KEY (id) REFERENCES book(id)
);

CREATE TABLE physical (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          weight_grams INTEGER,
                          stock_quantity INTEGER,

                          CONSTRAINT fk_physical_book FOREIGN KEY (id) REFERENCES book(id)
);

CREATE TABLE tag (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(255) UNIQUE NOT NULL,
                     description TEXT
);

CREATE TABLE book_tag (
                          book_id BIGINT NOT NULL,
                          tag_id BIGINT NOT NULL,

                          CONSTRAINT pk_book_tag PRIMARY KEY (book_id, tag_id),

                          CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES book (id),
                          CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL
);

-- 1. Tabela de Compras (Histórico definitivo)
CREATE TABLE purchase (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          book_id BIGINT NOT NULL,
                          purchase_date TIMESTAMP NOT NULL,
                          amount_paid DECIMAL(10,2) NOT NULL,

    -- Chaves Estrangeiras garantem que não podemos vender para um usuário fantasma ou um books deletado
                          CONSTRAINT fk_purchase_user FOREIGN KEY (user_id) REFERENCES users(id),
                          CONSTRAINT fk_purchase_book FOREIGN KEY (book_id) REFERENCES book(id)
);

-- 2. Tabela de Empréstimos (Transação com ciclo de vida)
CREATE TABLE loan (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      book_id BIGINT NOT NULL,
                      loan_date TIMESTAMP NOT NULL,
                      expected_return_date TIMESTAMP NOT NULL,
                      status VARCHAR(20) NOT NULL,

                      CONSTRAINT fk_loan_user FOREIGN KEY (user_id) REFERENCES users(id),
                      CONSTRAINT fk_loan_book FOREIGN KEY (book_id) REFERENCES book(id)
);