CREATE TABLE authors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        biography TEXT
);

CREATE TABLE books (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      authors_id BIGINT NOT NULL,
                      price DECIMAL(10,2) NOT NULL,
                      pages INTEGER NOT NULL,
                      genre VARCHAR(255) NOT NULL,
                      publication_date DATE,

                      CONSTRAINT fk_authors FOREIGN KEY (authors_id) REFERENCES authors(id)
);

CREATE TABLE ebooks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       size_mb DOUBLE PRECISION,
                       watermark VARCHAR(255),

                       constraint fk_ebooks_books FOREIGN KEY (id) REFERENCES books(id)
);

CREATE TABLE physical (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          weight_grams INTEGER,
                          stock_quantity INTEGER,

                          CONSTRAINT fk_books_physical FOREIGN KEY (id) REFERENCES books(id)
);

CREATE TABLE tags (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(255) UNIQUE NOT NULL,
                     description TEXT
);

CREATE TABLE books_tags (
                          books_id BIGINT NOT NULL,
                          tags_id BIGINT NOT NULL,

                          CONSTRAINT pk_book_tag PRIMARY KEY (books_id, tags_id),

                          CONSTRAINT fk_book FOREIGN KEY (books_id) REFERENCES books (id),
                          CONSTRAINT fk_tag FOREIGN KEY (tags_id) REFERENCES tags (id)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL
);

-- 1. Tabela de Compras (Histórico definitivo)
CREATE TABLE purchases (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          users_id BIGINT NOT NULL,
                          books_id BIGINT NOT NULL,
                          purchase_date TIMESTAMP NOT NULL,
                          amount_paid DECIMAL(10,2) NOT NULL,

    -- Chaves Estrangeiras garantem que não podemos vender para um usuário fantasma ou um books deletado
                          CONSTRAINT fk_purchase_user FOREIGN KEY (users_id) REFERENCES users(id),
                          CONSTRAINT fk_purchase_book FOREIGN KEY (books_id) REFERENCES books(id)
);

-- 2. Tabela de Empréstimos (Transação com ciclo de vida)
CREATE TABLE loans (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      users_id BIGINT NOT NULL,
                      books_id BIGINT NOT NULL,
                      loan_date TIMESTAMP NOT NULL,
                      expected_return_date TIMESTAMP NOT NULL,
                      status VARCHAR(20) NOT NULL,

                      CONSTRAINT fk_loan_user FOREIGN KEY (users_id) REFERENCES users(id),
                      CONSTRAINT fk_loan_book FOREIGN KEY (books_id) REFERENCES books(id)
);